on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Build and deploy API"
    runs-on: ubuntu-latest

    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host digitalocean
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out latest source code
        run: ssh digitalocean 'cd ~/safe-cycle/ && git fetch && git reset --hard origin/master'
        
      - name: Build application
        run: ssh digitalocean 'export NVM_DIR=$HOME/.nvm && source $NVM_DIR/nvm.sh && export NODE_ENV=production && cd ~/safe-cycle/ && yarn install && yarn build'
        
      - name: Restart the server
        run: ssh digitalocean 'export NVM_DIR=$HOME/.nvm && source $NVM_DIR/nvm.sh && pm2 restart api'
