on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Build and deploy API"
    runs-on: ubuntu-latest

    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Pull master and deploy
        run: ssh staging 'cd /home/safecycle/safe-cycle/ && git restore yarn.lock && git pull && yarn install && yarn build && pm2 restart api'
        
