on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 01 */2 *"

jobs:
  update_segments:
    name: "Renew HTTPS certificate"
    runs-on: ubuntu-latest

    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_ROOT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Pause server
        run: ssh staging 'runuser -l safecycle -c "pm2 stop api"'
      
      - name: Renew certs
        run: ssh staging 'cerbot renew && cp -rfL /etc/letsencrypt/live/safecycle.xyz/. /home/safecycle/certificates && chown -R safecycle:safecycle /home/safecycle/certificates/'
        
      - name: Restart server
        if: always()
        run: ssh staging 'runuser -l safecycle -c "pm2 restart api"'
        
