on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmrc
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.NVMRC }}"
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Build BRouter
        run: yarn build-brouter
        
      - name: Start BRouter
        run: yarn brouter
      
      - name: Install node modules
        run: yarn
      
      - name: Run tests
        run: yarn test
