on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.NVMRC }}'

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          distribution: temurin
          java-version: 17

      - name: Build BRouter
        run: yarn build-brouter

      - name: Download segment files for test
        run: bash ./brouter/scripts/update_segments_test.sh

      - name: Install node modules
        run: yarn

      - name: Start MongoDB server
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 5.0.8

      - name: Start BRouter
        run: yarn brouter &

      - name: Run tests
        run: yarn test
